name: belocal_travel_app_community_3002578953
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  belocal_travel_app_community_3002578953_f2f:
    git: https://f2f.bostonux.com/packages/belocal_travel_app_community_3002578953_f2f
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
